export const FILTER = {
  MIN_SALARY_LPA: 10,
  // Keep only roles a 0-2 yrs candidate can apply to. Jobs that never mention
  // experience are kept — we can't tell, and the title excludes seniors anyway.
  MAX_EXPERIENCE_YEARS: 2,
  INCLUDE_KEYWORDS: [
    "SDE",
    "Software Engineer",
    "Full Stack",
    "Full-Stack",
    "Backend",
    "Node",
    "Node.js",
    "React",
    "Frontend",
    "Front-end",
    "JavaScript",
    "TypeScript",
    "MERN",
    "Software Developer",
    "Staff Engineer",
  ] as const,
  EXCLUDE_KEYWORDS: [
    "10+ years",
    "senior",
    "staff",
    "lead",
    "manager",
    "architect",
    "PHP",
    "WordPress",
    "Angular only",
    "Java only",
    "Principal",
    "Director",
    "VP of Engineering",
    ".NET only",
    "Ruby on Rails only",
  ] as const,
  PREFERRED_LOCATIONS: [
    "remote",
    "bangalore",
    "bengaluru",
    "india",
    "work from home",
    "wfh",
    "hybrid",
  ] as const,
  // A location naming a foreign region is rejected even if it says "remote" —
  // "Fully remote - Canada" is not applyable from India.
  EXCLUDE_LOCATIONS: [
    "canada",
    "usa",
    "u.s.",
    "united states",
    "america",
    "united kingdom",
    "europe",
    "emea",
    "latam",
    "germany",
    "france",
    "poland",
    "netherlands",
    "ireland",
    "spain",
    "portugal",
    "israel",
    "singapore",
    "australia",
    "japan",
    "china",
    "brazil",
    "mexico",
    "dubai",
    "uae",
    "philippines",
    "vietnam",
    "indonesia",
  ] as const,
  SALARY_NOT_MENTIONED: "Not mentioned",
} as const;
