export const FILTER = {
  MIN_SALARY_LPA: 10,
  INCLUDE_KEYWORDS: [
    'SDE',
    'Software Engineer',
    'Full Stack',
    'Full-Stack',
    'Backend',
    'Node',
    'Node.js',
    'React',
    'Frontend',
    'Front-end',
    'JavaScript',
    'TypeScript',
    'MERN',
    'Software Developer',
  ] as const,
  EXCLUDE_KEYWORDS: [
    '10+ years',
    'senior only',
    'lead',
    'manager',
    'PHP',
    'WordPress',
    'Angular only',
    'Java only',
    'Staff Engineer',
    'Principal',
    'Director',
    'VP of Engineering',
    '.NET only',
    'Ruby on Rails only',
  ] as const,
  PREFERRED_LOCATIONS: [
    'remote',
    'bangalore',
    'bengaluru',
    'india',
    'work from home',
    'wfh',
    'hybrid',
  ] as const,
  SALARY_NOT_MENTIONED: 'Not mentioned',
} as const;
